package confluence

import (
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/phuc-nt/dandori/internal/integrations"
	"github.com/phuc-nt/dandori/internal/learn"
	"github.com/phuc-nt/dandori/internal/store"
)

// Reporter posts the fleet report to Confluence (UC3), deduped per day.
type Reporter struct {
	St      *store.Store
	Client  *Client
	Guard   *integrations.Guard
	SpaceID string
	Parent  string
	Window  int
}

// Post builds and publishes today's fleet report. Returns the page id,
// "dry-run" when the guard blocked the write, or "" when deduped.
func (r *Reporter) Post(actor string) (string, error) {
	date := time.Now().UTC().Format("2006-01-02")
	dedup := "confluence:report:" + date
	var n int
	r.St.DB.QueryRow(`SELECT count(*) FROM notifications WHERE dedup = ?`, dedup).Scan(&n)
	if n > 0 {
		return "", nil // already posted today
	}
	title := "Dandori fleet report " + date
	body, err := BuildReportHTML(r.St, r.Window)
	if err != nil {
		return "", err
	}
	if !r.Guard.Allow("create confluence page", title) {
		return "dry-run", nil
	}
	pageID, err := r.Client.CreatePage(r.SpaceID, r.Parent, title, body)
	if err != nil {
		return "", err
	}
	r.St.DB.Exec(`INSERT INTO notifications(kind, dedup, sent_at, detail)
		VALUES('confluence', ?, ?, ?) ON CONFLICT(dedup) DO NOTHING`, dedup, store.Now(), pageID)
	return pageID, nil
}

// BuildReportHTML renders the fleet snapshot as Confluence storage HTML:
// leaderboard, ROI, CFR, open flags. Data comes straight from learn — the
// same engine the console uses.
func BuildReportHTML(st *store.Store, windowDays int) (string, error) {
	board, err := learn.Leaderboard(st, windowDays)
	if err != nil {
		return "", err
	}
	cfr, err := learn.CFR(st, windowDays)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	esc := html.EscapeString

	fmt.Fprintf(&b, "<h2>Fleet leaderboard (%dd window)</h2>", windowDays)
	b.WriteString("<table><tbody><tr><th>Agent</th><th>Grade</th><th>Composite</th><th>Runs</th><th>Cost</th><th>Useful %</th></tr>")
	var totalCost float64
	for _, row := range board {
		grade := row.Grade.Letter
		if row.Grade.Uncalibrated {
			grade += "*"
		}
		totalCost += row.CostUSD
		fmt.Fprintf(&b, "<tr><td>%s</td><td>%s</td><td>%.0f</td><td>%d</td><td>$%.2f</td><td>%.0f%%</td></tr>",
			esc(row.AgentName), grade, row.Composite, row.Runs, row.CostUSD, row.ROI.UsefulPct)
	}
	b.WriteString("</tbody></table>")

	fmt.Fprintf(&b, "<h2>Spend &amp; quality</h2><p>Total cost: <strong>$%.2f</strong> · AI change-failure rate: <strong>%.0f%%</strong> (%s)</p>",
		totalCost, cfr.Value, esc(cfr.Formula))

	flags, err := openFlags(st)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "<h2>Open flags (%d)</h2>", len(flags))
	if len(flags) > 0 {
		b.WriteString("<ul>")
		for _, f := range flags {
			fmt.Fprintf(&b, "<li>run %s — %s</li>", esc(f[0]), esc(f[1]))
		}
		b.WriteString("</ul>")
	} else {
		b.WriteString("<p>None.</p>")
	}
	b.WriteString("<p><em>Generated by Dandori — every number traces to raw events in the console.</em></p>")
	return b.String(), nil
}

func openFlags(st *store.Store) ([][2]string, error) {
	rows, err := st.DB.Query(`SELECT COALESCE(run_id,''), COALESCE(reason,'') FROM flags WHERE status='open' ORDER BY id DESC LIMIT 20`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out [][2]string
	for rows.Next() {
		var f [2]string
		if err := rows.Scan(&f[0], &f[1]); err != nil {
			return nil, err
		}
		out = append(out, f)
	}
	return out, rows.Err()
}
